name: Auto Deploy Alumni Portal Frontend App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install SSH and SSHPASS
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Remote Server
        env:
          EPS_SSH_USER: ${{ secrets.EPS_SSH_USER }}
          EPS_SSH_PASSWORD: ${{ secrets.EPS_SSH_PASSWORD }}
          EPS_SSH_IPADDR: ${{ secrets.EPS_SSH_IPADDR }}
        run: |
          sshpass -p "$EPS_SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $EPS_SSH_USER@$EPS_SSH_IPADDR << 'EOF'
            cd /alumniportal/AlumniPFrontendEPS
            docker-compose down
            docker-compose up -d --build
          EOF
